# Generated by Django 4.2.5 on 2023-09-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicando', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Old Dojo', max_length=255),
            preserve_default=False,
        ),
    ]
