# Generated by Django 4.2.5 on 2023-09-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Athor',
            new_name='Author',
        ),
    ]
