# Generated by Django 4.2.5 on 2023-09-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0002_rename_athor_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='lat_name',
            new_name='last_name',
        ),
    ]
