# Generated by Django 4.2.5 on 2023-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0003_rename_lat_name_author_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='NO NOTES', max_length=255),
            preserve_default=False,
        ),
    ]
